replicaCount: 1

image:
  repository: 024848485298.dkr.ecr.us-west-2.amazonaws.com/microservicea
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: calculator-app
  type: clusterIP
  port: 80
  targetPort: 5000



configMapData:
  app_name: "calculator-app"
  log_level: "debug"

secretData:
  app_name: "calculator-app"
  db_password: "supersecretpassword"
  
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 50
  memoryUtilization: 50

ingress:
  enabled: true
  host: calulator-app
  name: calculator-app
  scheme: internet-facing 
  # Can be set to 'internal' if needed
resources:
  requests:
    memory: "500m"
    cpu: "500m"
    
nodeSelector: {}

tolerations: []

affinity: {}
