replicaCount: 1

image:
  repository: 024848485298.dkr.ecr.us-west-2.amazonaws.com/microservicea
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80 # The port on which the LoadBalancer will listen
  targetPort: 5000 # The port your service will route to



configMapData:
  app_name: "calculator-app"
  log_level: "debug"

secretData:
  app_name: "calculator-app"
  db_password: "supersecretpassword"
  
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 50
  memoryUtilization: 50


resources:
  requests:
    memory: "500m"
    cpu: "500m"
    
nodeSelector: {}

tolerations: []

affinity: {}
