replicaCount: 1

image:
  repository: 024848485298.dkr.ecr.us-west-2.amazonaws.com/microserviceb
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: calculator-app
  type: LoadBalancer
  port: 80
  targetPort: 5000

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization: 50
  memoryUtilization: 50

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
