replicaCount: 1

image:
  repository: microserviceb/microserviceb
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: calculator-app
  type: LoadBalancer
  port: 80
  targetPort: 5000
# values.yaml
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization: 50
  memoryUtilization: 50

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
