replicaCount: 1

image:
  repository: 024848485298.dkr.ecr.us-west-2.amazonaws.com/microservicea
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: calculator-app
  type: LoadBalancer
  port: 80
  targetPort: 5000

configMapData:
  app_name: "calculator-app"
  log_level: "debug"

secretData:
  app_name: "calculator-app"
  db_password: "supersecretpassword"
  
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 50
  memoryUtilization: 50

ingress:
  enabled: false

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
    limits:
    memory: "2Gi"
    cpu: "1"
  
nodeSelector: {}

tolerations: []

affinity: {}
