apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets
spec:
  backendType: secretsManager
  data:
    - key: MySecret
      name: my-secret-key
  # Optionally specify a template to customize the Kubernetes secret
  template:
    type: Opaque
