apiVersion: v1
kind: Service
metadata:
  name: my-microservice
spec:
  type: ClusterIP
  selector:
    app: calculator-app # Ensure this matches the labels on your pods
  ports:
    - port: 80
      targetPort: 80
