apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: calculator-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30000  # Example NodePort; ensure it is within the allowed range (30000-32767)
  selector:
    app: calculator-app
