apiVersion: v1
kind: Service
metadata:
  name: my-microservice
spec:
  type: NodePort
  selector:
    app: my-release # Ensure this matches the labels on your pods
  ports:
    - port: 80
      targetPort: 5000
