apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }} # This annotation is required to specify the use of ALB
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb" # Correct annotation for ALB
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing" # Set ALB scheme
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health" # Health check path
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "HTTP" # Backend protocol
spec:
  type: {{ .Values.service.type }}
  ports:
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Release.Name }}
