apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }} # This annotation is required to specify the use of ALB
  annotations:
    alb.ingress.kubernetes.io/scheme: "internet-facing" # Scheme for ALB
    alb.ingress.kubernetes.io/healthcheck-path: "/health" # Optional: Health check path for ALB
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  type: {{ .Values.service.type }}
  ports:
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Release.Name }}
