replicaCount: 1

image:
  repository: yerubandiram/salary
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: salary-app
  type: LoadBalancer
  port: 80
  targetPort: 4000
# values.yaml
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization: 50
  memoryUtilization: 50
  
ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
